import React,{useState,useRef,useEffect} from 'react';
import {Check,ArrowRight,Compass,SlidersHorizontal} from 'lucide-react';
import {startingPlans,recommendPlan} from '../catalog/planning.js';

export function PlanCards({kind,selected,onSelect,onHelp,onCompare}){
 const plans=startingPlans.filter(p=>p.kind===kind);
 return <div className="starting-plans"><div className="plan-toolbar"><div><h3>Choose a starting direction.</h3><p>Every plan is adjustable. These are priorities to discuss, not fixed parts packages.</p></div><div><button type="button" className="builder-text-button" onClick={onHelp}><Compass size={19}/>Help me choose</button><button type="button" className="builder-text-button" onClick={onCompare}><SlidersHorizontal size={19}/>Compare plans</button></div></div><div className="plan-grid">{plans.map(p=><button type="button" key={p.id} className={`plan-card ${p.id===selected?'chosen':''}`} aria-pressed={p.id===selected} onClick={()=>onSelect(p)}><div className="plan-image"><img src={`/images/${p.image.replace(/\.[^.]+$/,'-640.webp')}`} alt="" loading="lazy"/><span>{p.id===selected?<><Check size={18}/>Your starting plan</>:'Explore this direction'}</span></div><div><h3>{p.name}</h3><strong>{p.line}</strong><p>{p.description}</p><span className="plan-pick">{p.id===selected?'Selected — adjust next':'Start here'}<ArrowRight size={19}/></span></div></button>)}</div></div>;
}
export function PlanChooser({kind,initial={},onChoose}){
 const [answers,setAnswers]=useState(initial),[stage,setStage]=useState(0);
 const heading=useRef(null);useEffect(()=>{heading.current?.focus({preventScroll:true});},[stage]);
 const questions=[{key:'load',title:'What stays on your truck?',options:[['occasional','Gear goes on for trips.','Lighter between adventures.'],['permanent','Equipment stays onboard.','Tools, drawers, racks or camp gear.'],['unsure','I’m still figuring it out.','The team can help assess the load.']]},{key:'trips',title:'How far does the plan take you?',options:[['weekend','Daily driving & weekends','A workday and a way out.'],['multi-day','Multi-day trips','More time outdoors.'],['remote','Longer, remote travel','A custom scope deserves a conversation.']]},{key:'priority',title:'What do you want to make easier?',options:[['flexibility','Keep my options open','A flexible starting point.'],['work','Carrying tools & equipment','Work, hauling and access.'],['camp','Setting up camp','Storage and a simpler routine.'],['camper','Supporting my camper','The truck and camper, together.']]}];
 const question=questions[stage],recommendation=recommendPlan(kind,answers),plan=startingPlans.find(p=>p.id===recommendation.id);
 return <div className="plan-chooser">{stage<3?<><p className="builder-muted">Question {stage+1} of 3</p><h3 ref={heading} tabIndex={-1}>{question.title}</h3><div className="chooser-options">{question.options.map(([value,label,line])=><button type="button" key={value} onClick={()=>{setAnswers({...answers,[question.key]:value});setStage(stage+1);}}><strong>{label}</strong><span>{line}</span><ArrowRight size={20}/></button>)}</div>{stage>0&&<button type="button" className="builder-text-button" onClick={()=>setStage(stage-1)}>Back to the previous question</button>}</>:<><span className="eyebrow">Your planning direction</span><h3 ref={heading} tabIndex={-1}>{plan.name}</h3><p>{recommendation.reason}</p><p className="builder-muted">This matches your answers, not verified vehicle fitment. You’ll adjust the priorities next.</p><button type="button" className="button button-primary builder-full" onClick={()=>onChoose(plan,answers)}>Use this starting plan <ArrowRight size={18}/></button><button type="button" className="builder-text-button" onClick={()=>setStage(0)}>Change my answers</button></>}</div>;
}
export function PlanComparison({kind,onChoose}){return <div className="plan-comparison">{startingPlans.filter(p=>p.kind===kind).map(p=><article key={p.id}><h3>{p.name}</h3><p>{p.description}</p><ul>{p.priorities.map(priority=><li key={priority}>{priority}</li>)}</ul><button type="button" className="builder-text-button" onClick={()=>onChoose(p)}>Start with {p.name}<ArrowRight size={17}/></button></article>)}<p className="builder-muted">The planning direction is not a parts list, fitment approval or a price promise.</p></div>;}
