import React,{useState,useEffect,useRef} from 'react';
import {Menu,X,Phone,ChevronDown,ChevronLeft,ChevronRight,Plus,MapPin,Maximize2,Check} from 'lucide-react';
import {P,pages,nav,services,serviceImages,serviceKeys,inquiry,external} from './routes.js';
import './styles.css';
import HomeExperience from './HomeExperience.jsx';
import {useExperienceMotion} from './useExperienceMotion.js';
import Builder from './builder/Builder.jsx';
import {Inquiry,Confirmation} from './Inquiry.jsx';
import {vehicleRoutes} from './builder/domain.js';
import {Flatbeds,Campers,Work,Projects,SuperUte,ServiceHub,Guide,Contact,Consultation,Packages,Sitemap} from './Pages.jsx';
import './expressive.css';
import {FullPhotoHero, CustomerProof} from './Journey.jsx';
import './journey.css';
import './character.css';
import './next-level.css';
import {ServiceDetail} from './ServiceDetail.jsx';
import {ProjectIndex,BuildStoryPage,RangerStoryPage} from './BuildStories.jsx';
import {AboutStory} from './Story.jsx';
import {actionMotionProps} from './actionMotion.js';
import './action-motion.css';
import './service-signatures.css';
const img=(name)=>'/images/'+name;
export function LinkButton({to,children,light=false,outline=false,...props}){return <a href={to} className={`button ${outline?'button-outline':light?'button-light':'button-primary'}`} {...actionMotionProps(to)} {...props}>{children}</a>}
function Photo({file,alt,className='',eager=false,...props}){return <img className={className} src={img(file.replace(/\.[^.]+$/, '-1000.webp'))} srcSet={`${img(file.replace(/\.[^.]+$/, '-640.webp'))} 640w, ${img(file.replace(/\.[^.]+$/, '-1000.webp'))} 1000w, ${img(file.replace(/\.[^.]+$/, '-1600.webp'))} 1600w`} sizes="(max-width: 600px) 100vw, 50vw" alt={alt} width="1600" height="1000" loading={eager?'eager':'lazy'} fetchPriority={eager?'high':'auto'} {...props}/>}
function quoteForPath(path){
  const service=services.find(item=>item.path===path);
  if(path==='/'||path===P.services)return '#start-project';
  if(service)return inquiry('service',{service:serviceKeys[service.id]});
  if(path===P.rangerStory)return inquiry('flatbed',{project:'ranger-flatbed'});
  if(path===P.quote)return '#main';
  if(path===P.dillon)return inquiry('service',{service:'suspension',project:'dillon-f250'});
  if(path===P.camperStory)return inquiry('camper',{project:'alaskan-camper'});
  if(path===P.ute)return inquiry('flatbed',{project:'super-ute'});
  if(path===P.camper)return inquiry('camper');
  if(path===P.work)return inquiry('work');
  if([P.about,P.contact,P.projects,P.quote].includes(path))return inquiry('general');
  return inquiry('flatbed');
}
function Header({path,motionOff,reduced,toggleMotion}){const quoteTarget=quoteForPath(path);const [open,setOpen]=useState(false);const panel=useRef();useEffect(()=>{if(!open)return;const handle=e=>{if(e.key==='Escape'){setOpen(false);document.getElementById('menu-button')?.focus()}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle)},[open]);return <><a className="skip-link" href="#main">Skip to content</a><div className="preview-bar"><span>Website preview</span><button type="button" className="motion-toggle" onClick={toggleMotion} aria-pressed={motionOff} disabled={reduced} aria-label={reduced?"Reduced motion is enabled by your device":motionOff?"Turn motion on":"Pause motion"}><span className="motion-dot" aria-hidden="true"/>{reduced?"Reduced motion":motionOff?"Motion paused":"Motion on"}</button></div><header className="site-header"><a href="/" className="brand" aria-label="Next Jump Outfitters home"><img src={img('logo.png')} alt="Next Jump Outfitters" width="200" height="73"/><span className="logo-word">NEXT JUMP<small>OUTFITTERS</small></span></a><nav aria-label="Main navigation" className="desktop-nav">{nav.map(([label,url])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{label}</a>)}</nav><div className="header-actions"><a className="call-link" href="tel:+12533010028" aria-label="Call the shop at 253 301 0028"><Phone size={18}/></a><LinkButton to={quoteTarget}>{path===P.builder||vehicleRoutes.some(v=>v.path===path)?"Get help":"Get a quote"}</LinkButton><button className="icon-button menu-button" id="menu-button" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav id="mobile-menu" ref={panel} className="mobile-nav" aria-label="Mobile navigation">{[...nav,['Camper Setups',P.camper],["Buyer’s Guide",P.guide],['Get a Quote',quoteTarget],['Contact & Visit',P.contact]].map(([label,url])=><a key={url} href={url} onClick={()=>setOpen(false)}>{label}</a>)}</nav>}</header></>}
function Footer({path}){return <footer><div className="footer-top container"><div className="footer-brand"><img src={img('logo-white.png')} alt="Next Jump Outfitters" width="210" height="77"/><p>Built around your truck.<br/>Based in Tacoma, Washington.</p><span className="eyebrow">Veteran-owned &amp; operated</span></div><div><h3>Find your next build</h3>{[['Explore Flatbeds',P.flatbeds],['Camper Setups',P.camper],['Work & Business',P.work],['Plan your build',P.builder],["Buyer’s Guide",P.guide]].map(([l,u])=><a key={u} href={u}>{l}</a>)}</div><div><h3>At the shop</h3>{[['Installation Services',P.services],['Our Work',P.projects],['Our Story',P.about],['Get a Quote',quoteForPath(path)],['Design Consultation',P.consult],['All pages',P.sitemap]].map(([l,u])=><a key={u} href={u}>{l}</a>)}</div><div><h3>Come talk trucks</h3><a href="tel:+12533010028">(253) 301-0028</a><a href="mailto:theteam@nextjumpoutfitters.com">theteam@nextjumpoutfitters.com</a><a href={P.contact}>3721 S Lawrence St<br/>Tacoma, WA 98409</a><p>Mon–Fri, 8am–5pm<br/>Closed weekends</p></div></div><div className="footer-bottom container"><span>© 2026 Next Jump Outfitters</span><div>{external.map(([l,u])=><a key={u} href={u}>{l}<span className="sr-only"> on the live Shopify store</span></a>)}</div><span>Retail &amp; policies open the live store.</span></div></footer>}
function Closing({title='You don’t need a parts list to start.',body='Tell us about your truck and what you want to change. We’ll help you work out the next step.',to=inquiry(),label='Talk through my build'}){return <section className="closing"><div className="container"><div><span className="eyebrow">YOUR TRUCK. YOUR NEXT CHAPTER.</span><h2>{title}</h2><p>{body}</p></div><LinkButton to={to}>{label}</LinkButton></div></section>}
function Breadcrumb({label}){return <nav aria-label="Breadcrumb" className="breadcrumb container"><a href="/">Home</a><span>/</span><span aria-current="page">{label}</span></nav>}
function SectionTitle({kicker,title,text,link,label}){return <div className="section-heading"><div>{kicker&&<span className="eyebrow">{kicker}</span>}<h2>{title}</h2>{text&&<p>{text}</p>}</div>{link&&<a href={link} className="text-link">{label}</a>}</div>}
function GenericHero({page,file,action,to,secondary}){return file?<><FullPhotoHero file={file} alt={`${page.label} at Next Jump Outfitters`} kicker={'NEXT JUMP / '+page.label.toUpperCase()} title={page.headline} description={page.intro} action="Get a quote" to={to} secondary={secondary?{label:secondary[0],to:secondary[1]}:undefined}/><div id="page-content"><Breadcrumb label={page.label}/></div></>:<><Breadcrumb label={page.label}/><section className="page-hero container text-hero"><div><h1>{page.headline}</h1><p>{page.intro}</p>{action&&<LinkButton to={to}>{action}</LinkButton>}</div></section></>}
function ContentPage({page}){const file=serviceImages[page.id]||({P02:'hero.png',P03:'camper.jpg',P04:'work.png',P27:'shop.png',P28:'shop.png'}[page.id]);const context=page.id==='P03'?'camper':page.id==='P04'?'work':serviceImages[page.id]?'service':'flatbed';const to=inquiry(context,serviceKeys[page.id]?{service:serviceKeys[page.id]}:{});return <div className="expressive-page"><GenericHero page={page} file={file} action={page.id==='P02'?'Plan your build':'Discuss my project'} to={page.id==='P02'?P.builder:to}/><div className="container content-sections">{page.sections.filter(s=>!s.heading.startsWith('See a relevant')&&!s.heading.startsWith('Meet the team')).map((s,i)=><section key={s.id} id={s.id==='business'?'business':s.id==='overlanding'?'overlanding':s.id} className="editorial-row"><span className="row-number">{String(i+1).padStart(2,'0')}</span><h2>{s.heading}</h2><div>{s.body.map((b,j)=><p key={j}>{b}</p>)}</div></section>)}</div><CustomerProof context={page.id} to={to}/><Closing to={to} label="Get a quote"/></div>}
export default function App({url='/'}){const motion=useExperienceMotion();const u=new URL(url,'http://localhost');const path=u.pathname.replace(/\/$/,'')||'/';const page=pages.find(p=>p.path===path);return <><Header path={path} {...motion}/><main id="main" tabIndex={-1}>{path==='/'?<HomeExperience/>:path===P.builder||vehicleRoutes.some(v=>v.path===path)?<><h1 className="sr-only">{vehicleRoutes.find(v=>v.path===path)?.label||"Plan your flatbed"}</h1><Builder routeVehicle={vehicleRoutes.find(v=>v.path===path)||null} query={Object.fromEntries(u.searchParams)}/></>:path===P.quote?<><h1 className="sr-only">Build or installation inquiry</h1><Inquiry query={Object.fromEntries(u.searchParams)}/></>:path===P.confirmation?<Confirmation/>:path===P.flatbeds?<Flatbeds/>:path===P.camper?<Campers/>:path===P.work?<Work/>:path===P.projects?<ProjectIndex/>:path===P.rangerStory?<RangerStoryPage/>:path===P.dillon?<BuildStoryPage kind="dillon"/>:path===P.camperStory?<BuildStoryPage kind="camper"/>:path===P.ute?<SuperUte/>:path===P.services?<ServiceHub/>:path===P.guide?<Guide/>:path===P.about?<AboutStory/>:path===P.contact?<Contact/>:path===P.consult?<Consultation/>:path===P.packages?<Packages/>:path===P.sitemap?<Sitemap vehicles={vehicleRoutes}/>:page&&serviceKeys[page.id]?<ServiceDetail page={page}/>:page?<ContentPage page={page}/>:<section className="section container text-hero"><span className="eyebrow">404 / THIS TRAIL ENDS HERE</span><h1>Let’s get you back to your build.</h1><p>That page isn’t part of this preview.</p><LinkButton to={P.builder}>Find my truck</LinkButton></section>}</main><Footer path={path}/></>}
