import React,{useState,useRef,useEffect} from 'react';
import {ArrowUpRight,Play,X,ArrowRight} from 'lucide-react';
import {FullPhotoHero,JourneyImage,JourneyAction} from './Journey.jsx';
import {P,inquiry} from './routes.js';
const builds=[
  {name:'The Super Ute.',tag:'2017 FORD F-250 · COLLABORATION',file:'ute-front.jpg',alt:'Completed Super Ute Ford F-250 on a forest road',to:P.ute,text:'Flatbed. Side storage. Topper. A complete camp setup, built with Adventure Built, Flated and TRUKD.',label:'Explore the build'},
  {name:'Dillon’s F-250.',tag:'1993 FORD F-250 · CUSTOMER PROJECT',file:'flagship-dillon-f250.webp',alt:'Dillon Collins’s lifted green and white 1993 Ford F-250',to:P.dillon,text:'A lift for a truck other shops had turned away. See the finished rig and hear from its owner.',label:'See the lift project'},
  {name:'Room for the camper.',tag:'ALASKAN CAMPER · SETUP EXAMPLE',file:'flagship-camper-slide-in.jpg',alt:'Alaskan camper and side storage on a Next Jump branded Ford flatbed truck',to:P.camperStory,text:'A published Next Jump setup showing how the camper, platform and storage share one truck.',label:'Explore the setup'},
  {name:'Small truck. Big ideas.',tag:'FORD RANGER · FLATBED SETUP',file:'flagship-ranger-flatbed.jpg',alt:'Ford Ranger with a Next Jump midsize flatbed, dropsides and underbody storage in a grassy field',to:P.rangerStory,text:'A midsize truck with a different kind of bed. Get a closer look at the platform, dropsides and storage.',label:'See the Ranger setup'}
];
export function BuildStories({index=false}){return <section className={`build-stories container ${index?'build-stories-index':''}`} aria-labelledby="build-stories-heading"><div className="build-stories-heading"><div><span className="eyebrow">FROM OUR SHOP TO THE ROAD</span><h2 id="build-stories-heading">Good ideas.<br/><span className="trail-mark">Better in the wild.</span></h2></div><p>Look at the details. Find your starting point. Every truck has a different job to do.</p></div><div className="build-story-grid">{builds.map((b,i)=><a className={`build-story build-story-${i}`} href={b.to} key={b.to}><div className="build-story-photo"><JourneyImage file={b.file} alt={b.alt} sizes="(max-width: 800px) 100vw, 60vw"/><span className="build-story-open" aria-hidden="true"><ArrowUpRight/></span></div><div className="build-story-copy"><span className="eyebrow">{b.tag}</span><h3>{b.name}</h3><p>{b.text}</p><span className="text-link">{b.label} <ArrowRight size={20} aria-hidden="true"/></span></div></a>)}</div></section>}
export function ProjectIndex(){return <div className="expressive-page flagship-projects"><FullPhotoHero file="ute-tent.jpg" alt="Super Ute at camp in a wide open golden landscape" kicker="NEXT JUMP / OUR WORK" title={<>Real trucks.<br/><em>Real possibilities.</em></>} description="Explore the builds, installations and setups that turn a truck into something personal. Then let’s plan yours." action="Talk through my project" to={inquiry('general')} secondary={{to:'#build-stories-heading',label:'See the projects'}}/><div id="page-content"><BuildStories index/></div><ProjectNext/></div>}
function ProjectNext({context='general',project='',title='What would you change about your truck?',body='Bring the part you like, the equipment you use, or the job your truck needs to do.'}){return <section className="project-next"><div className="container"><div><span className="eyebrow">YOUR TRUCK IS NEXT</span><h2>{title}</h2><p>{body}</p></div><JourneyAction to={inquiry(context,{...(project?{project}:{}),...(project==='dillon-f250'?{service:'suspension'}:{})})}>Plan something like this</JourneyAction></div></section>}
export function RangerStoryPage(){
 const to=inquiry('flatbed',{project:'ranger-flatbed'});
 return <div className="expressive-page flagship-story flagship-ranger"><FullPhotoHero file="flagship-ranger-flatbed.jpg" alt={builds[3].alt} kicker="FORD RANGER / PHOTOGRAPHED SETUP" title={<>Small truck.<br/><em>Big ideas.</em></>} description="A Ford Ranger with a Next Jump midsize flatbed. Dropsides, underbody storage and a platform ready for your next idea." to={to} action="Plan my Ranger setup" secondary={{to:'#ranger-details',label:'Look at the details'}} caption="Actual Next Jump setup. Configuration varies by truck."/>
 <div id="page-content" className="container project-story-body"><nav className="project-story-back" aria-label="Breadcrumb"><a href={P.projects}>Our work</a><span aria-hidden="true">/</span><span>Ford Ranger flatbed setup</span></nav><div className="project-story-intro" id="ranger-details"><h2>Your truck.<br/><span className="trail-mark">A different bed.</span></h2><div><p>You don’t need a full-size truck to start thinking differently about your bed. This Ranger is pictured with Next Jump’s midsize 5-foot flatbed, enclosed sides and storage below the deck.</p><p>Look at the space around the platform. Think about what you carry, where you need access and how the truck should work between trips. Those are the details to bring into your own build.</p></div></div><div className="project-full-photo"><JourneyImage file="flagship-ranger-flatbed.jpg" alt={builds[3].alt}/></div><div className="project-considerations">{[['A different platform','An aluminum bed gives this Ranger a new starting point for its equipment.'],['Storage below','The photographed underbody box keeps storage separate from the main deck.'],['Plan the whole setup','Discuss bed access, mounting, clearances and vehicle ratings before choosing equipment.']].map(([h,p],i)=><div key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div><p className="project-source-note">Photographed setup from <a href="https://www.nextjumpoutfitters.com/collections/aluminum-flatbeds-truck-beds">Next Jump’s aluminum flatbed collection</a>. Fit and equipment need confirmation for your specific Ranger.</p><div className="project-related"><h3>Start with the truck you drive.</h3><p>Explore the flatbed components, then tell the shop which details matter to you.</p><JourneyAction to={P.flatbeds}>Explore aluminum flatbeds</JourneyAction></div></div><ProjectNext context="flatbed" project="ranger-flatbed" title="What could your Ranger carry?" body="Bring your vehicle details and the gear you want to take. Let’s work through the setup together."/></div>
}
export function BuildStoryPage({kind}){
 const isLift=kind==='dillon';const to=inquiry(isLift?'service':'camper',isLift?{service:'suspension',project:'dillon-f250'}:{project:'alaskan-camper'});
 return <div className={`expressive-page flagship-story ${isLift?'flagship-lift':'flagship-camper'}`}><FullPhotoHero file={isLift?'flagship-dillon-f250.webp':'flagship-camper-slide-in.jpg'} alt={isLift?builds[1].alt:builds[2].alt} kicker={isLift?'CUSTOMER PROJECT / 1993 FORD F-250':'SETUP EXAMPLE / ALASKAN CAMPER'} title={isLift?<>A classic truck.<br/><em>A different stance.</em></>:<>Take your room<br/><em>on the road.</em></>} description={isLift?'Dillon wanted to lift his 1993 F-250. When other shops declined, he brought the project to Next Jump.':'An Alaskan camper, an aluminum flatbed and side storage. A closer look at one of Next Jump’s published camper setups.'} to={to} action={isLift?'Plan my suspension upgrade':'Discuss my camper setup'} secondary={{to:P.projects,label:'See more work'}} caption={isLift?'Dillon’s actual truck, published with his review.':'Next Jump setup photograph. Exact fit varies by vehicle.'}/>
 <div id="page-content" className="container project-story-body"><nav className="project-story-back" aria-label="Breadcrumb"><a href={P.projects}>Our work</a><span aria-hidden="true">/</span><span>{isLift?'Dillon’s F-250':'Alaskan camper setup'}</span></nav>
 <div className="project-story-intro"><h2>{isLift?<>Keep the truck.<br/><span className="trail-mark">Build the idea.</span></>:<>More than<br/><span className="trail-mark">a place to sleep.</span></>}</h2><div><p>{isLift?'An older truck can make an installation less straightforward. Dillon’s published review describes a team willing to take on his F-250 lift and keep him informed through the project.':'This Next Jump Ford shows a camper above the flatbed, with storage running along the sides. The useful question is how your own camper, gear and everyday routine should fit together.'}</p><p>{isLift?'The finished truck is pictured here. Start your own suspension conversation with your vehicle details, current equipment and the change you want to make.':'Bring the camper model you own—or the ones you’re comparing. The team can review the truck, mounting, clearances and installation together.'}</p></div></div>
 {isLift?<><figure className="owner-voice"><blockquote>“Great communication, great pricing, and amazing quality.”</blockquote><figcaption><strong>Dillon Collins</strong><span>1993 Ford F-250 lift · Customer review</span></figcaption><a href="https://www.nextjumpoutfitters.com/pages/lift-suspension-installation">Read the published project and review <ArrowUpRight size={18} aria-hidden="true"/></a></figure><div className="project-full-photo"><JourneyImage file="flagship-dillon-f250.webp" alt={builds[1].alt}/></div></>:<><div className="project-full-photo"><JourneyImage file="flagship-camper-slide-in.jpg" alt={builds[2].alt}/></div><div className="project-considerations">{[['The camper','Exact model, dimensions and mounting requirements.'],['The truck','Vehicle ratings, loaded weight and existing equipment.'],['The gear','What you need to reach with the camper installed.']].map(([h,p],i)=><div key={h}><span>0{i+1}</span><h3>{h}</h3><p>{p}</p></div>)}</div><p className="project-source-note">Photographed setup example from <a href="https://www.nextjumpoutfitters.com/pages/flatbeds-for-overland-and-off-road-campers">Next Jump’s camper collection</a>. Your truck and camper need their own compatibility review.</p></>}
 <div className="project-related"><h3>{isLift?'Work through the upgrade.':'Make your camper plan concrete.'}</h3><p>{isLift?'Explore the suspension service, then share your year, make, model and intended use.':'Compare camper types and build a starting configuration around your truck.'}</p><JourneyAction to={isLift?'/pages/lift-suspension-installation':P.camper}>{isLift?'See suspension services':'Explore camper setups'}</JourneyAction></div></div><ProjectNext context={isLift?'service':'camper'} project={isLift?'dillon-f250':'alaskan-camper'} title={isLift?'Have a truck you want to keep building?':'Let’s build around your camper.'}/></div>
}
export function WalkaroundFilm(){const [open,setOpen]=useState(false);const ref=useRef(null);useEffect(()=>{if(!open)return;const prior=document.activeElement,overflow=document.body.style.overflow;ref.current.showModal();document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;prior?.focus()}},[open]);return <section className="walkaround-film container"><button className="film-poster" type="button" onClick={()=>setOpen(true)} aria-label="Play the Super Ute walkaround"><JourneyImage file="ute-tent.jpg" alt="Super Ute camp setup in an open landscape at sunset"/><span className="film-play"><Play size={32} fill="currentColor" aria-hidden="true"/></span><span className="film-title"><span>ADVENTURE BUILT / SUPER UTE</span><strong>See it work.<br/>Watch the walkaround.</strong></span></button><p>Watch the original Adventure Built tour. Video loads from YouTube when opened.</p>{open&&<dialog ref={ref} className="film-dialog" aria-label="Super Ute walkaround video" onCancel={e=>{e.preventDefault();setOpen(false)}}><div><span>Super Ute · Adventure Built</span><button type="button" aria-label="Close walkaround video" onClick={()=>setOpen(false)}><X/></button></div><iframe title="Adventure Built Super Ute walkaround" src="https://www.youtube-nocookie.com/embed/06HrZY39eVk?rel=0" allow="fullscreen; picture-in-picture; encrypted-media" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/><a href="https://www.youtube.com/watch?v=06HrZY39eVk">Open the original video on YouTube <ArrowUpRight size={18}/></a></dialog>}</section>}
