import content from './content.json';
export const P={rangerStory:'/pages/ford-ranger-flatbed-setup',dillon:'/pages/dillon-f250-lift-project',camperStory:'/pages/alaskan-camper-flatbed-setup',home:'/',flatbeds:'/pages/overland-aluminum-flatbed-truck-bodies',camper:'/pages/flatbeds-for-overland-and-off-road-campers',work:'/pages/flatbeds-for-work-and-business',builder:'/pages/flatbed-build-price-by-vehicle',guide:'/pages/flatbed-buyers-guide',quote:'/pages/book-install-services-or-get-a-quote',consult:'/pages/book-a-build-consultation',projects:'/pages/our-work',ute:'/pages/the-super-ute-collaboration-build',services:'/pages/overland-off-road-installation-services-tacoma-wa',about:'/pages/about-us',contact:'/pages/contact-us',confirmation:'/pages/build-request-received',packages:'/pages/flatbed-packages',sitemap:'/sitemap'};
export const pages=content.filter(p=>!p.path.includes('{')).map(p=>({...p,publication:p.id==='P05'?'gated':'preview',indexable:false}));
export const nav=[['Flatbeds',P.flatbeds],['Installation Services',P.services],['Our Work',P.projects],['About',P.about]];
export const services=pages.filter(p=>/P(1[6-9]|2[0-6])/.test(p.id));
export const serviceImages={P16:'suspension.png',P17:'racks.png',P18:'wheels.png',P19:'power.png',P20:'lighting.png',P21:'tent.jpg',P22:'camper.jpg',P23:'wash.png',P24:'boat.png',P25:'boat.png',P26:'trailer.jpg'};
export const serviceKeys={P16:'suspension',P17:'bumpers-racks',P18:'wheels-tires',P19:'power',P20:'lighting',P21:'rooftop-tent',P22:'camper',P23:'detailing',P24:'boat-detail',P25:'marine',P26:'trailer'};
export function inquiry(context='flatbed',extras={}){return P.quote+'?'+new URLSearchParams({context,...extras}).toString()}
export const external=[['Shop gear','https://www.nextjumpoutfitters.com/collections/all'],['Privacy policy','https://www.nextjumpoutfitters.com/policies/privacy-policy'],['Terms of service','https://www.nextjumpoutfitters.com/policies/terms-of-service'],['Refund policy','https://www.nextjumpoutfitters.com/policies/refund-policy']];
